<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Madhuri-Laptop" failures="1" tests="5" name="Personal Loan" time="0.075" errors="0" timestamp="2024-07-30T14:57:38 EDT">
  <testcase classname="test.day2" name="wTest2" time="0.01"/>
  <testcase classname="test.day1" name="day1Demo" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.day1Demo(day1.java:42)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- day1Demo -->
  <testcase classname="test.day2" name="wTest1" time="0.004"/>
  <testcase classname="test.day1" name="day1Parameter" time="0.002"/>
  <testcase classname="test.day1" name="day1Test" time="0.007"/>
  <testcase classname="test.day2" name="Day2Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Day2Test2 -->
</testsuite> <!-- Personal Loan -->
